"""Grade a cheap model's answer against that run's `metrics.json` (EVAL-01).

WHY `tools/` AND NOT `scripts/`. This is not a pipeline stage. It runs *after*
the report, on a file the model produced; it has no `--spec`/`--out` contract;
it is never in `run_all`'s four-stage sequence; and `scripts/` is the directory
the agentskills runtime loads, the one `mypy scripts --strict` treats as the
frozen stage surface, and the one the contract tests enumerate. A fifth CLI
there would make `scripts/` mean two things. It also imports **nothing from
the skill** - it is a reader - so it needs no `sys.path` shim and no `common`
import, which is what makes the no-network proof a one-line AST check.

It reads `metrics.json` and NOTHING else. Not `charts.json`, not `report.md`,
not `series.csv`. The answer is graded against the same single source of truth
the report was written from (ANAL-06, `references/CONTRACTS.md` §2), which is
the only way "the model did not invent a number" is a mechanical claim rather
than a promise.

===========================================================================
THE NUMBER RULE, IN FULL (an unstated rule is a noisy check)
===========================================================================

1. The SOURCE SET is every numeric leaf of `metrics.json`, plus `as_of` and
   every `period.start` / `period.end` **as whole strings** - the dates
   themselves, not their components. A date is not a measurement.

2. For each source number `v` the ACCEPTED FORMS are precomputed and the list
   is CLOSED - it is a fixed set of spellings, not a tolerance:

       str(v)                      f"{v:+.1f}"        f"{v:,.1f}"
       f"{v:+}"                    f"{v:.1f}"         f"{v:,.0f}"
       str(int(v))  (integral v)   str(round(v, 0))   str(round(v, 1))

   plus a SPACE-grouped variant of each grouped form, generated by replacing
   `,` with U+00A0 and then with U+0020 (so `1 720 628` is a spelling of
   1720628), plus a COMMA-DECIMAL variant of each ungrouped form (`38,5` is a
   spelling of 38.5, which the Ukrainian document language needs).
   **There is no tolerance band.** A band is precisely what lets a wrong number
   through: if 16.7 passes because 16.6 would also pass, the check is
   decorative.

   A NEGATIVE value is quoted WITH its sign. There is deliberately no unsigned
   form: a bare `38.5` and a `+38.5` are the same token here, so accepting the
   magnitude would let an answer claim a 38.5% increase against a source of
   -38.5 - the sign error this property exists to catch.

3. TOKENISATION is one regex: an optional sign (`-`, `+`, or U+2212), a digit,
   then digits with optional `,` / U+00A0 / space grouping, then an optional
   `.` plus digits, then an optional `%`. A comma is a DECIMAL separator only
   when it cannot be a thousands group (preceded by a digit, followed by
   exactly three), so `52,5` is 52.5 and `1,720` is 1720. The line number and
   character offset of every match are captured so a failure can point at the
   exact place.

4. EXEMPT, and here is why each is exempt:

   - a token that is part of an ISO date (`YYYY-MM-DD`), a `YYYYMMDD` date, an
     `HH:MM` time, or a dotted version like `0.1.0`, decided by testing the
     token's SURROUNDING characters - a date component is not a measurement,
     and `2026` in `2026-09-20` is not a pageview count;
   - a token immediately preceded by `%` inside a word;
   - a token inside a `%XX` percent-encoding triplet, so a Czech or Ukrainian
     slug can be quoted verbatim;
   - a token bounded by a LETTER on both sides, so the article `N8n` can be
     named. A measurement in prose is always bounded by whitespace or
     punctuation, so this cannot reach a real figure;
   - a bare list-bullet marker, which the regex can never see anyway.

5. NORMALISATION of a surviving token: fold U+2212 to ASCII `-`, strip a
   leading `+` (but NOT a leading `-`), strip a trailing `%`, delete every `,`
   / U+00A0 / space that is a thousands group, then `float()`. The token
   PASSES if its normalised form is in the accepted set of ANY source value.
   Otherwise it FAILS, and the report names the token, `line N offset M`, and
   the three numerically closest source values - so an operator can see at a
   glance whether the model wrote a stale number or a computed one.

6. THE SOURCE SET ALSO READS THE RUBRIC PROSE. `confidence_reasons` (a list of
   strings) and `seasonality.note` are quoted verbatim by contract, so the
   integers inside them are legitimate sources: `period at least 91 days` and
   `fewer than two aligned 365-day halves are available` are mandatory content
   that property 1 must not fail. The scan is a bare digit run — no sign, no
   decimal, no percent — so a reason string cannot inject a value the tool
   would not itself have produced, and only those two keys are read.

DELIBERATELY NOT COVERED, and these belong in the runbook's "what a failure
means" list rather than being hidden here:

   - a number spelled in words ("півтора", "one hundred");
   - a number inside an embedded image, which no text reader can see;
   - **a percentage the model derived from two `metrics.json` values.** This is
     a real gap. A derived ratio is a new number, and property 1 will call it a
     novel number even though the model computed it honestly. The remedy is the
     interpretation file's rule, not a looser check.

Exit codes: 0 all four properties pass, 1 at least one fails, 2 a usage or
input problem. The tool's own problems are therefore distinguishable from the
answer's problems.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections.abc import Iterator, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Stamped into every regression stub, so a fixture promoted months later says
# which validator produced it. Bump on any change to the four properties.
VERSION = "0.1.0"

# The four EVAL-01 properties, in report order, printed in this order so a
# reader can diff two runs line for line. Adding a fifth property means adding
# it here and writing the check beside the others; the runbook documents this
# tuple as the contract.
PROPERTIES = (
    "numbers_present",
    "low_is_hypothesis",
    "as_of_present",
    "sources_and_limitations",
)

# MARKER CHECK, NOT A SEMANTIC ONE. A model that writes "зріс" in a sentence
# that also carries "гіпотеза" PASSES this property, and a model that writes a
# bare conclusion in a language this table does not cover FAILS for the wrong
# reason. Neither is a defect of the check: the human read is still the final
# word, which is exactly why the roadmap scopes EVAL-01 to `partial` rather
# than `full`. To cover another language, extend BOTH tuples - a hedge list
# without a matching assertion list would let a conclusion through.
#
# Lower-cased substrings, covering the two languages the report stage supports
# (`uk`, `en`). Ukrainian first, because the committed document language is
# Ukrainian.
HEDGE_MARKERS = (
    "гіпотез",
    "можливо",
    "схоже",
    "не впевн",
    "низьк",
    "low confidence",
    "hypothes",
    "possibly",
    "may ",
    "appears",
    "not certain",
    "unclear",
)

ASSERTION_MARKERS = (
    "зріс",
    "зростає",
    "росте",
    "впав",
    "падає",
    "підтвердж",
    "rising",
    "grew",
    "growing",
    "increased",
    "declin",
    "dropped",
)

# Property 4. Each group must MATCH and must have a non-blank, non-heading body
# after it, so an empty "## Джерела" heading is a failure rather than a pass.
# Case-insensitive; the `re.IGNORECASE | re.UNICODE` flags are what let a
# Cyrillic heading match without transliteration.
_SECTION_FLAGS = re.IGNORECASE | re.UNICODE
SECTION_PATTERNS: dict[str, tuple[str, ...]] = {
    "sources": (r"джерел", r"sources?", r"data source"),
    "limitations": (r"обмеження", r"limitations?", r"припущення"),
}

# One regex for every number the answer contains. Grouping separators are the
# three forms a human actually types: comma, no-break space, plain space.
#
# The sign class carries U+2212 MINUS SIGN alongside ASCII `-` (FINDING-04).
# It is a different code point, so without it the regex never matched it as a
# sign at all and `−38.5%` was read as the POSITIVE `38.5`. `-` is listed first
# so the alternation prefers it where both are possible.
NUMBER_PATTERN = re.compile(
    r"(?P<sign>[-+−]?)(?P<int>\d[\d, ]*)(?:\.(?P<frac>\d+))?(?P<pct>%)?"
)


# A date, a time, a compact date, or a dotted version: matched against the
# characters AROUND a token, never inside it, because the token regex already
# consumed the digits.
_DATE_CONTEXT = re.compile(
    r"(?:\d{4}-\d{1,2}-\d{1,2}|\d{8}|\d{1,2}:\d{2}|\d+\.\d+\.\d+)"
)
_SENTENCE_SPLIT = re.compile(r"[.!?\n]+")
_WORD_BOUNDARY_BEFORE = re.compile(r"[A-Za-zА-Яа-яІіЇїЄєҐґ0-9._%+-]$")
_ENCODING_TRIPLET = re.compile(r"%[0-9A-Fa-f]{2}")

# U+2212 MINUS SIGN. A typographic minus is what a word processor and a
# Ukrainian keyboard produce, and it is a DIFFERENT code point from ASCII `-`,
# so the token regex never saw it as a sign at all: `-52.5%` failed as `-52.5`
# while `−52.5%` was read as the positive `52.5`.
_TYPOGRAPHIC_MINUS = "\u2212"

# A bare integer inside reason prose. Deliberately narrower than
# `NUMBER_PATTERN`: no sign, no decimal, no percent, no grouping. A reason
# string must not be able to inject a value the tool would not otherwise have
# produced as a source. Only the two rubric keys above are scanned, so no
# free-form string elsewhere in `metrics.json` becomes a number source.
_REASON_INTEGER = re.compile(r"\d+")


@dataclass
class PropertyResult:
    """One property's verdict, and the detail that explains it."""

    name: str
    passed: bool
    detail: str = ""
    offending_token: str | None = None
    # True when the property PASSED because there was nothing to check. A vacuous
    # pass is printed as a NOTE so it is visible in the transcript rather than
    # indistinguishable from a real one.
    vacuous: bool = False
    excerpt: str = ""


@dataclass
class ValidationReport:
    """All four results plus the paths they were graded against."""

    results: list[PropertyResult] = field(default_factory=list)
    metrics_path: Path | None = None
    answer_path: Path | None = None
    metrics_sha256: str = ""
    answer_sha256: str = ""


# --------------------------------------------------------------------------
# Source-value collection
# --------------------------------------------------------------------------


def _numeric_leaves(node: Any, dates: set[str]) -> list[float]:
    """Every numeric leaf of the document, plus every date string, collected.

    `dates` is filled with the WHOLE date strings (`as_of`, `period.start`,
    `period.end`), never their components: a date component is not a
    measurement, and treating `2026` as a pageview count would make the check
    noisy on every date in the answer.

    A STRING leaf is also scanned for integers, but only under a key that the
    rubric populates with prose. `confidence_reasons` and `seasonality.note`
    are strings by contract, and SKILL.md requires the answer to quote them
    verbatim - so `period at least 91 days` and `no recurring peak months
    identified` are mandatory content. Before this, `_numeric_leaves` skipped
    every string, and an honest answer that obeyed the quoting rule failed
    property 1 on the rubric's own thresholds (FINDING-04).

    The scan is a bounded integer pattern, deliberately NOT the full
    `NUMBER_PATTERN`: a reason string must not be able to inject a decimal,
    a sign or a percent into the source set that the rest of the tool would
    not itself have produced. Only the keys below are scanned, so no
    free-form string elsewhere in `metrics.json` is a number source.
    """
    found: list[float] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key in {"as_of", "start", "end"} and isinstance(value, str):
                dates.add(value)
            elif key == "confidence_reasons" and isinstance(value, list):
                # A list of rubric strings, one per scoring line.
                found.extend(
                    float(number)
                    for entry in value
                    if isinstance(entry, str)
                    for number in _REASON_INTEGER.findall(entry)
                )
            elif key == "note" and isinstance(value, str):
                # `seasonality.note` is the sibling case: one rubric string.
                found.extend(float(number) for number in _REASON_INTEGER.findall(value))
            else:
                found.extend(_numeric_leaves(value, dates))
    elif isinstance(node, list):
        for item in node:
            found.extend(_numeric_leaves(item, dates))
    elif isinstance(node, bool):
        pass
    elif isinstance(node, (int, float)):
        found.append(float(node))
    return found


def _accepted_forms(value: float) -> set[str]:
    """Every spelling of `value` this validator accepts. A CLOSED set.

    The list is fixed and total: grouping separators, a `+` sign, a `.1f`
    rendering and integral roundings. Nothing here widens a value, and nothing
    here introduces a tolerance.

    Two additions over the original list, both of which are new SPELLINGS of an
    existing source value rather than a widened tolerance - the closed-set
    property this docstring asserts is intact:

    * the COMMA decimal rendering, because the document language is Ukrainian
      and a comma is the decimal separator there;
    * nothing else. In particular there is deliberately NO unsigned form of a
      negative value, even though "fell by 38.5%" is how a person writes a
      decline. A bare `38.5` and a `+38.5` are the SAME token to this
      checker, so accepting the unsigned magnitude would let an answer claim a
      38.5% INCREASE against a source value of -38.5 - precisely the sign error
      property 1 exists to catch, and no surrounding-word analysis can tell
      the two apart here. A decline is therefore quoted WITH its sign, which is
      what `manual.md` A.8 already does.

    All were touched for FINDING-04, where a declining series had no quotable
    spelling at all. A tolerance band is still forbidden: 16.7 does not pass
    because 16.6 would.
    """
    forms: set[str] = set()
    forms.add(str(value))
    forms.add(f"{value:+}")
    forms.add(f"{value:+.1f}")
    forms.add(f"{value:.1f}")
    forms.add(f"{value:,}")
    forms.add(f"{value:,.1f}")
    forms.add(f"{value:,.0f}")
    if value.is_integer():
        forms.add(str(int(value)))
    forms.add(str(round(value, 0)))
    forms.add(str(round(value, 1)))
    grouped: set[str] = set()
    for form in forms:
        if "," in form:
            grouped.add(form.replace(",", " "))
            grouped.add(form.replace(",", " "))
    # The comma-as-decimal rendering is added only where a comma is a DECIMAL
    # separator, which is a single comma followed by one or two digits. Adding
    # it to a grouped form (`1,720`) would invent a 1.720 reading, so each
    # ungrouped form is converted explicitly instead.
    decimal_comma: set[str] = set()
    for form in forms:
        if "." in form and "," not in form:
            decimal_comma.add(form.replace(".", ","))
    return forms | grouped | decimal_comma



def _strip_separators(value: str) -> str:
    """Delete every grouping separator: `,`, no-break space and plain space."""
    for separator in (",", " ", " "):
        value = value.replace(separator, "")
    return value


def _normalise(token: str) -> float:
    """Strip the display decoration off a token and read it as a number.

    The SIGN IS KEPT, and this is the FINDING-04 fix. The previous version
    stripped a leading `+` or `-` alike, so `-52.5` was read as `52.5` while
    `_accepted_forms` only ever emitted signed spellings of a negative value -
    the value's own form was not in the accepted set, and no answer could quote
    a decline. Only `+` is dropped now, because it carries no information that
    the magnitude does not.

    U+2212 is folded to ASCII `-` first: it is a different code point, so the
    token regex never saw it as a sign at all and `−52.5%` was read as the
    POSITIVE `52.5`.

    A COMMA is read as a decimal separator only when it cannot be a thousands
    group: a real group is preceded by a digit and followed by exactly three.
    `52,5` is 52.5 (the Ukrainian spelling); `1,720` is 1720.
    """
    cleaned = token.strip().replace(_TYPOGRAPHIC_MINUS, "-")
    if cleaned.startswith("+"):
        cleaned = cleaned[1:]
    cleaned = cleaned.rstrip("%")
    if "," in cleaned and not re.fullmatch(r"\d{1,3}(,\d{3})+(\.\d+)?", cleaned):
        cleaned = cleaned.replace(",", ".")
    return float(_strip_separators(cleaned))


def _encoding_spans(text: str) -> list[tuple[int, int]]:
    """Character spans of every `%XX` percent-encoding triplet in the text.

    `references/CONTRACTS.md` §1 carries the Czech article slug verbatim in its
    encoded form, `P%C5%AFst_p%C5%99eru%C5%A1ovan%C3%BD`, and an answer quoting the
    article it analysed will quote it. The number regex reads `5%` out of `C5%AF`
    and `1` out of `%A1`, so without this rule every honest answer that names
    the article fails property 1 on its own slug.

    The overlap test is narrow by construction: a real percentage's token ENDS
    at its `%`, so it never intersects the triplet that starts there, while a
    token inside a triplet always does. `16.7%` and `50% done` stay checked.
    """
    return [(match.start(), match.end()) for match in _ENCODING_TRIPLET.finditer(text)]


def _is_exempt(text: str, match: re.Match[str], encodings: Sequence[tuple[int, int]]) -> bool:
    """Whether a matched token is a date, a time, a version, or an encoding."""
    start, end = match.span()
    window = text[max(0, start - 12) : min(len(text), end + 12)]
    if _DATE_CONTEXT.search(window):
        return True
    if any(start < encoding_end and encoding_start < end for encoding_start, encoding_end in encodings):
        return True
    prefix = text[:start]
    if prefix and _WORD_BOUNDARY_BEFORE.search(prefix) and prefix.endswith("%"):
        return True
    # FINDING-04: digits inside a proper name. `N8n` is an article title, and
    # the answer has to be able to name the article it analysed - the same
    # reason a percent-encoded slug is exempt above.
    #
    # The rule is deliberately narrow: a LETTER on BOTH sides. A measurement in
    # prose is always bounded by whitespace or punctuation, so this cannot
    # exempt a real number. It is NOT "any alphabetic neighbour", which would
    # silently exempt every figure in a sentence; `test_the_proper_name_exemption_is_narrow`
    # pins that half of the claim by requiring a letter-bounded token with no
    # letter neighbour to still be checked.
    if (
        start > 0
        and end < len(text)
        and text[start - 1].isalpha()
        and text[end].isalpha()
    ):
        return True
    return False


def _nearest(value: float, pool: Sequence[float]) -> list[float]:
    """The three DISTINCT pool values numerically closest to `value`.

    Deduplicated because `metrics.json` carries a value twice wherever a
    `clean` variant repeats its `pct`/`abs` - reporting "5.7, 5.7, 3.5" would
    spend two of three slots on one number.
    """
    distinct = sorted(set(pool))
    return sorted(distinct, key=lambda candidate: abs(candidate - value))[:3]


def _iter_tokens(text: str) -> Iterator[tuple[str, re.Match[str]]]:
    """Yield `(token, match)` for every non-exempt number, with its position."""
    encodings = _encoding_spans(text)
    for match in NUMBER_PATTERN.finditer(text):
        if _is_exempt(text, match, encodings):
            continue
        yield match.group(0), match


# --------------------------------------------------------------------------
# The four properties
# --------------------------------------------------------------------------


def check_numbers(text: str, metrics: dict[str, Any]) -> PropertyResult:
    """Property 1: every number in the answer is present in `metrics.json`."""
    dates: set[str] = set()
    pool = _numeric_leaves(metrics, dates)
    accepted: set[float] = set()
    for value in pool:
        for form in _accepted_forms(value):
            # The accepted side is normalised by `_normalise` ITSELF, not by a
            # hand-inlined variant of it. The FINDING-04 fix added signed,
            # unsigned and comma-decimal spellings, and the two sides must
            # agree on all three: a pool built with `_strip_separators` alone
            # would read the accepted form "38,5" as 385 while the answer's
            # identical token was read as 38.5, and every comma-decimal
            # spelling would fail against its own source value.
            try:
                accepted.add(_normalise(form))
            except ValueError:  # pragma: no cover - a form that is not numeric
                continue
    # The date strings themselves are legitimate content and are compared as
    # WHOLE STRINGS - a date is not a number, so it never goes through
    # `_normalise`. (Its components are exempt by rule 4 anyway; this is the
    # second, independent way the same content is accepted.)
    accepted_dates = {_strip_separators(value) for value in dates}

    lines = text.splitlines()
    for token, match in _iter_tokens(text):
        if _strip_separators(token.lstrip("+").rstrip("%")) in accepted_dates:
            continue
        try:
            value = _normalise(token)
        except ValueError:
            continue
        if value in accepted:
            continue
        line_number = text.count("\n", 0, match.start()) + 1
        line_start = text.rfind("\n", 0, match.start()) + 1
        offset = match.start() - line_start
        context = lines[line_number - 1].strip() if line_number <= len(lines) else ""
        nearest = ", ".join(str(value_) for value_ in _nearest(value, pool))
        return PropertyResult(
            name="numbers_present",
            passed=False,
            detail=(
                f"token {token!r} at line {line_number} offset {offset} matches no "
                f"metrics.json value; nearest source values: {nearest or 'none'}; "
                f"line reads: {context[:200]}"
            ),
            offending_token=token,
            excerpt=context[:400],
        )
    return PropertyResult(
        name="numbers_present",
        passed=True,
        detail=f"{len(pool)} source values, every number in the answer matched one",
    )


def check_low_is_hypothesis(text: str, metrics: dict[str, Any]) -> PropertyResult:
    """Property 2: a `low` series is phrased as a hypothesis, never a conclusion.

    A MARKER check, not a semantic one - see the module-level note on
    `HEDGE_MARKERS`. A `metrics.json` with no `low` series passes with the
    message `no low-confidence series to check`: a vacuous pass is STATED, not
    hidden, and the exit code is still 0.
    """
    lowered = text.casefold()
    low_series = [
        series for series in metrics.get("series", []) if series.get("confidence") == "low"
    ]
    if not low_series:
        return PropertyResult(
            name="low_is_hypothesis",
            passed=True,
            detail="no low-confidence series to check",
            vacuous=True,
        )

    sentences = [part.strip() for part in _SENTENCE_SPLIT.split(text) if part.strip()]
    for series in low_series:
        needles = [
            str(series.get("label", "")).casefold(),
            str(series.get("series_id", "")).casefold(),
        ]
        needles = [needle for needle in needles if needle]
        mentioning = [sentence for sentence in sentences if any(n in sentence.casefold() for n in needles)]
        series_id = str(series.get("series_id", "?"))
        if not mentioning:
            return PropertyResult(
                name="low_is_hypothesis",
                passed=False,
                detail=f"low series {series_id} is not mentioned at all",
                excerpt="",
            )
        hedged = [s for s in mentioning if any(m in s.casefold() for m in HEDGE_MARKERS)]
        if not hedged:
            unhedged = next(
                (
                    s
                    for s in mentioning
                    if any(m in s.casefold() for m in ASSERTION_MARKERS)
                ),
                mentioning[0],
            )
            return PropertyResult(
                name="low_is_hypothesis",
                passed=False,
                detail=(
                    f"low series {series_id} is mentioned but no sentence about it carries a "
                    f"hedge marker; it reads: {unhedged[:200]}"
                ),
                excerpt=unhedged[:400],
            )
        for sentence in mentioning:
            folded = sentence.casefold()
            asserted = any(marker in folded for marker in ASSERTION_MARKERS)
            hedged_here = any(marker in folded for marker in HEDGE_MARKERS)
            if asserted and not hedged_here:
                return PropertyResult(
                    name="low_is_hypothesis",
                    passed=False,
                    detail=(
                        f"low series {series_id} is asserted without a hedge in the same "
                        f"sentence: {sentence[:200]}"
                    ),
                    excerpt=sentence[:400],
                )
    del lowered
    return PropertyResult(
        name="low_is_hypothesis",
        passed=True,
        detail=f"{len(low_series)} low-confidence series, every mention hedged",
    )


def check_as_of_present(text: str, metrics: dict[str, Any]) -> PropertyResult:
    """Property 3: `as_of` is present, in its one canonical spelling.

    Unlike property 1, the `YYYYMMDD` form is NOT accepted here. This property
    is about the reader being able to tell how fresh the reading is, and a
    single canonical spelling is the point of it.
    """
    expected = str(metrics.get("as_of", ""))
    if not expected:
        return PropertyResult(
            name="as_of_present",
            passed=False,
            detail="metrics.json carries no as_of, so freshness cannot be stated",
        )
    if expected in text:
        return PropertyResult(
            name="as_of_present", passed=True, detail=f"as_of {expected} stated literally"
        )
    return PropertyResult(
        name="as_of_present",
        passed=False,
        detail=f"as_of {expected!r} does not appear in the answer, in any spelling",
        offending_token=expected,
    )


def _section_body(text: str, start: int) -> str:
    """The first non-blank, non-heading line after a heading match."""
    for line in text[start:].splitlines()[1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        return stripped
    return ""


def check_sources_and_limitations(text: str, metrics: dict[str, Any]) -> PropertyResult:
    """Property 4: a sources section and a limitations section, both non-empty.

    A heading with an empty body is the failure this property exists to catch:
    "## Джерела" followed by nothing reads as compliance to a skim and is not.
    """
    del metrics
    missing: list[str] = []
    empty: list[str] = []
    for name, patterns in SECTION_PATTERNS.items():
        hit = None
        for pattern in patterns:
            compiled = re.compile(pattern, _SECTION_FLAGS)
            found = compiled.search(text)
            if found is not None:
                hit = found
                break
        if hit is None:
            missing.append(name)
        elif not _section_body(text, hit.start()):
            empty.append(name)
    if missing:
        return PropertyResult(
            name="sources_and_limitations",
            passed=False,
            detail=f"no section found for: {', '.join(missing)}",
        )
    if empty:
        return PropertyResult(
            name="sources_and_limitations",
            passed=False,
            detail=f"section heading present but the body is empty for: {', '.join(empty)}",
        )
    return PropertyResult(
        name="sources_and_limitations",
        passed=True,
        detail="sources and limitations sections both present and non-empty",
    )


CHECKS = {
    "numbers_present": check_numbers,
    "low_is_hypothesis": check_low_is_hypothesis,
    "as_of_present": check_as_of_present,
    "sources_and_limitations": check_sources_and_limitations,
}


# --------------------------------------------------------------------------
# Regression stub
# --------------------------------------------------------------------------

STUB_KEYS = (
    "version",
    "property",
    "metrics_sha256",
    "answer_sha256",
    "answer_filename",
    "detail",
    "offending_token",
    "created_from_metrics",
    "answer_excerpt",
)


def _write_stub(report: ValidationReport, result: PropertyResult, out_dir: Path) -> Path:
    """Write the promotion-shaped regression stub for one failing property.

    The shape is deliberately promotion-ready: a real failure becomes
    `tests/fixtures/eval/fail-<property>.example.json` by copying this file and
    replacing the excerpt, with NO edit to the schema. `metrics_sha256` is the
    binding field - a fixture that cannot be tied to the document it graded is
    not a regression fixture.
    """
    target_dir = out_dir / "eval" / "regression"
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{result.name}.example.json"
    document = {
        "version": VERSION,
        "property": result.name,
        "metrics_sha256": report.metrics_sha256,
        "answer_sha256": report.answer_sha256,
        "answer_filename": report.answer_path.name if report.answer_path else "",
        "detail": result.detail,
        "offending_token": result.offending_token,
        "created_from_metrics": str(report.metrics_path) if report.metrics_path else "",
        "answer_excerpt": result.excerpt[:400],
    }
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    os.replace(temporary, path)
    return path


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def validate(answer_text: str, metrics: dict[str, Any]) -> list[PropertyResult]:
    """Run all four properties, ALWAYS in `PROPERTIES` order.

    A silent property is an unchecked property, so the order and the count are
    part of the contract rather than an accident of the dict.
    """
    results: list[PropertyResult] = []
    for name in PROPERTIES:
        results.append(CHECKS[name](answer_text, metrics))
    return results


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Grade a cheap model's answer against that run's metrics.json (EVAL-01).",
        epilog=(
            "Exit 0 = every property passed. Exit 1 = at least one property failed. "
            "Exit 2 = a usage or input problem. This tool never calls a model and "
            "never touches the network; the live cheap-model run is the owner's step, "
            "and the runbook is in README.md."
        ),
    )
    parser.add_argument("--answer", required=True, help="the model's answer file (Markdown or text)")
    parser.add_argument("--out", required=True, help="the pipeline output directory holding metrics.json")
    parser.add_argument("--quiet", action="store_true", help="suppress PASS lines; keep FAIL lines")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """Grade one answer file. Returns 0, 1 or 2 - see the module docstring."""
    args = _parser().parse_args(argv)

    answer_path = Path(args.answer)
    metrics_path = Path(args.out) / "metrics.json"
    for path, label in ((answer_path, "answer"), (metrics_path, "metrics.json")):
        if not path.is_file():
            print(f"validate_answer: {label} not found: {path}", file=sys.stderr)
            return 2
    try:
        answer_bytes = answer_path.read_bytes()
        metrics_bytes = metrics_path.read_bytes()
    except OSError as error:
        print(f"validate_answer: could not read an input: {error}", file=sys.stderr)
        return 2
    try:
        metrics = json.loads(metrics_bytes.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        print(f"validate_answer: metrics.json is not readable JSON: {error}", file=sys.stderr)
        return 2
    if not isinstance(metrics, dict):
        print("validate_answer: metrics.json must be a JSON object", file=sys.stderr)
        return 2
    try:
        answer_text = answer_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        print(f"validate_answer: the answer file is not UTF-8: {error}", file=sys.stderr)
        return 2

    report = ValidationReport(
        metrics_path=metrics_path,
        answer_path=answer_path,
        metrics_sha256=hashlib.sha256(metrics_bytes).hexdigest(),
        answer_sha256=hashlib.sha256(answer_bytes).hexdigest(),
    )
    report.results = validate(answer_text, metrics)

    failures = [result for result in report.results if not result.passed]
    for result in report.results:
        if result.passed:
            if not args.quiet:
                print(f"PASS {result.name}")
        else:
            print(f"FAIL {result.name}: {result.detail}")
    for result in report.results:
        if result.vacuous:
            print(f"NOTE {result.name}: {result.detail}")

    for result in failures:
        stub = _write_stub(report, result, Path(args.out))
        print(f"wrote regression stub: {stub}")

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
